const { JSDOM } = require("jsdom");
const html = require("fs").readFileSync(require("path").join(__dirname, "../../dist/index.html"), "utf8");
const errors = []; const sleep = ms => new Promise(r => setTimeout(r, ms));
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.org/", beforeParse(w) { w.addEventListener("error", e => errors.push(e.message)); w.addEventListener("unhandledrejection", e => errors.push("rej " + e.reason));
  w.scrollTo = () => {}; w.HTMLElement.prototype.scrollIntoView = () => {}; w.HTMLCanvasElement.prototype.getContext = () => ({ clearRect() {}, fillRect() {} });
  w.fetch = async () => ({ ok: false }); } });
const w = dom.window, d = w.document, $ = s => d.querySelector(s), click = el => el.dispatchEvent(new w.MouseEvent("click", { bubbles: true }));
const txt = s => $(s) ? $(s).textContent.replace(/\s+/g, " ").trim() : "∅";
(async () => { await sleep(20);
  w.eval("surahSheet(1)"); await sleep(30);
  console.log("الفاتحة intro:", [...d.querySelectorAll("#dintro .dsec summary")].map(x => x.textContent).join(" | "), "| links:", d.querySelectorAll(".sheet a").length);
  console.log("  maqasid:", txt("#dintro .dsec .body").slice(0, 70)); click($("#closeSheet"));
  w.eval("surahSheet(2)"); await sleep(30); console.log("البقرة intro:", d.querySelectorAll("#dintro .dsec").length, "sections"); click($("#closeSheet"));
  w.eval("surahSheet(18)"); await sleep(30); console.log("الكهف (not fetched):", txt("#dintro")); click($("#closeSheet"));
  w.eval("openReader(1, 'meaning')"); await sleep(30); console.log("p1 meaning ijmali:", txt(".ijmali").slice(0, 60), "| asbab:", txt("#dasbab"));
  w.eval("openReader(1, 'tadabbur')"); await sleep(30); console.log("p1 tadabbur:", [...d.querySelectorAll("#rv .dsec summary")].map(x => x.textContent).join(" | "), "| today:", txt(".today .ayah"));
  w.eval("openReader(7, 'tadabbur')"); await sleep(30); console.log("p7 tadabbur (drafts fallback):", txt("#rv .topic").slice(0, 40), "| badge:", txt("#rv .badge"));
  w.eval("openReader(300, 'tadabbur')"); await sleep(30); console.log("p300:", txt("#rv").slice(0, 50));
  w.eval("openReader(7, 'meaning')"); await sleep(30); console.log("p7 meaning:", d.querySelectorAll(".ijmali").length, "ijmali |", txt("#dasbab").slice(0, 50));
  console.log("JS errors:", errors.length ? errors : "none");
})();
