const { JSDOM } = require("jsdom");
const html = require("fs").readFileSync(require("path").join(__dirname, "../../dist/index.html"), "utf8");
const errors = []; const sleep = ms => new Promise(r => setTimeout(r, ms));
const dom = new JSDOM(html, { runScripts: "dangerously", url: "https://example.org/", beforeParse(w) { w.addEventListener("error", e => errors.push(e.message)); w.addEventListener("unhandledrejection", e => errors.push("rej " + e.reason));
  w.scrollTo = () => {}; w.HTMLElement.prototype.scrollIntoView = () => {}; w.HTMLCanvasElement.prototype.getContext = () => ({ clearRect() {}, fillRect() {} }); w.fetch = async () => ({ ok: false }); } });
const w = dom.window, d = w.document, $ = s => d.querySelector(s), click = el => el.dispatchEvent(new w.MouseEvent("click", { bubbles: true }));
const txt = s => $(s) ? $(s).textContent.replace(/\s+/g, " ").trim() : "∅";
(async () => { await sleep(20);
  w.eval("openReader(7,'mushaf')");
  console.log("reader:", txt(".rtop .t"), "| tpanel:", !!$("#tpanel"), "| seg tabs:", !!$(".seg"), "| cta:", !!$(".recite-cta"));
  console.log("mutashabih rings:", d.querySelectorAll(".rd .end.m").length);
  click($("#pgNext")); console.log("next:", txt(".rtop .t small")); click($("#pgPrev")); console.log("prev:", txt(".rtop .t small"));
  const a48 = d.querySelector('.a[data-k="2:48"]'); click($("#rd")); console.log("tap → tools shown:", $("#rd").classList.contains("ui"));
  a48.dispatchEvent(new w.Event("pointerdown", { bubbles: true })); await sleep(520);
  console.log("long-press ayah → sheet:", !!$(".sheet"), d.querySelectorAll(".sheet .compare").length, "compare"); click($("#closeSheet"));
  console.log("immersive:", d.body.classList.contains("immersive"), "| tabs hidden via CSS class");
  click($("#hideSw")); console.log("hidden:", d.querySelectorAll(".lines.hide .w").length); click($("#hideSw"));
  click($("#more")); console.log("more options:", [...d.querySelectorAll("[data-o]")].map(b => b.querySelector("div").textContent).join(" | "));
  click(d.querySelector('[data-o="tadabbur"]')); await sleep(20); console.log("→ tadabbur seg:", !!$(".seg"), txt(".seg [aria-pressed=true]"));
  click(d.querySelector('[data-v="mushaf"]')); console.log("→ back to reading mode:", !!$("#rd"));
  click($("#more")); click(d.querySelector('[data-o="tafsir"]')); console.log("→ tafsir tab:", txt(".rtop .t").slice(0, 7), txt(".tfh .pick b"));
  w.eval("openReader(7,'mushaf')"); click($("#more")); click(d.querySelector('[data-o="tas"]')); console.log("→ tasmee:", txt(".target .grow").slice(0, 25));
  console.log("JS errors:", errors.length ? errors : "none");
})();
